name: Automatic Comment
on:
  issues:
    types: [opened]
permissions:
  contents: read

jobs:
  comment:
    permissions:
      issues: write
    name: Comment
    runs-on: ubuntu-latest
    steps:
      - name: Automatic Comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for the issue, we will take it into consideration! I/We are
            busy working on many types of features, please give us time to get
            back to you.
            
            To any amazing contributors: [issues labeled `bug`](https://github.com/Kaamkiya/devcli/issues?q=is%3Aopen+label%3Abug)
            are always up for grabs, but for feature requests, please wait until
            we add a `ready for dev` before starting to work on it.

            To claim an issue to work on, please leave a comment. If you've
            claimed the issue and need help, please create a discussion or
            reply to the issue. I will follow up.

            For full info on how to contribute, please check out our [contributing guide](../CONTRIBUTING.md).
